export const WINTER_BALANCE = {
  dailyFirewoodPerHeatedBuilding: 2.4,
  insulationConsumptionReduction: 0.65,
  occupantHeatBonus: 0.18,
  indoorHeatGainPerFirewood: 4.5,
  indoorTemperatureLag: 0.55,
  outdoorColdExposurePerTick: 0.012,
  indoorRecoveryPerTick: 0.025,
  hypothermiaHealthLossPerDay: 2.8,
  severeHypothermiaHealthLossPerDay: 7,
  illnessRecoveryWithCare: 9,
  repairWoodCost: 3,
  repairStoneCost: 1,
  insulationWoodCost: 4,
  firewoodConversionRate: 1,
  repairAmount: 18,
  insulationAmount: 12,
  minimumMigrationDay: 4,
  migrationExit: { x: 720, y: 260 },
} as const;
